// Generated by CoffeeScript 1.6.3
(function() {
  var slideToggle;

  slideToggle = function() {
    return $("#slideout").toggleClass("slide");
  };

  $(function() {
    return $("#slideoutTab").on('click', slideToggle);
  });

}).call(this);
